name: Build
on:
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: [ ubuntu-latest ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: npm install
        run: npm install
      - name: npm build
        run: npm run build
      - name: docker login
        env:
          CR_PAT: ${{ secrets.GH_TOKEN }}
        run: echo $CR_PAT | docker login ghcr.io -u grischastorch23 --password-stdin
      - name: docker build
        run: docker build -t react-test .
      - name: docker push
        run: docker push ghcr.io/grischastorch23/react-test:latest
