name: PR Guard
on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: [ ubuntu-latest ]

    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: npm install
        run: npm install
      - name: npm build
        run: npm run build
      - name: npm test
        run: npm run test
